services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: docker/dev-environments-javascript:stable-1
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

  mysql:
    container_name: peoria-fresh-database-devel
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33061:3306
    environment:
      - MYSQL_DATABASE=PFresh
      - MYSQL_ROOT_PASSWORD=whateverYouWantYourPasswordToBe
    volumes:
      - peoria-fresh-mysql-data:/var/lib/mysql

volumes:
  peoria-fresh-mysql-data:
