version: '3.9'

services:
  dev:
    container_name: peoria-fresh-backend-dev
    image: peoria-fresh-backend-dev
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - '4200:8080'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  prod:
    container_name: peoria-fresh-backend-prod
    image: peoria-fresh-backend-prod
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - '8000:8080'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  mysql:
    container_name: peoria-fresh-database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33061:3306
    environment:
      - MYSQL_DATABASE=PFresh
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - peoria-fresh-mysql-data:/var/lib/mysql

volumes:
  peoria-fresh-mysql-data:
